# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checksysR <- function(Gamma0, Gamma1, Psi, Pi, C) {
    .Call('_gensysR_checksysR', PACKAGE = 'gensysR', Gamma0, Gamma1, Psi, Pi, C)
}

gensysR <- function(Gamma0, Gamma1, Psi, Pi, C) {
    .Call('_gensysR_gensysR', PACKAGE = 'gensysR', Gamma0, Gamma1, Psi, Pi, C)
}

gensysR_qzdetails <- function(Gamma0, Gamma1, Psi, Pi, C) {
    .Call('_gensysR_gensysR_qzdetails', PACKAGE = 'gensysR', Gamma0, Gamma1, Psi, Pi, C)
}

